events {}

http {

    server {
        listen 80;

        location /profiles/ {
            proxy_pass http://profiles-service:3001/;
        }

        location /about/ {
            proxy_pass http://about-service:3002/;
        }
    }
}