version: "3.9"

services:
  profiles:
    image: milanasolyanka/lab5-profiles
    ports:
      - "3001:3001"
    networks:
      - mynetwork
    deploy:
      replicas: 1 # можно больше, если нужно масштабирование
      placement:
        constraints:
          - node.hostname == nodejs-server-profiles

  about:
    image: milanasolyanka/lab5-about
    ports:
      - "3002:3002"
    networks:
      - mynetwork
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == nodejs-server-about

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - mynetwork
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == nodejs-server-manager

networks:
  mynetwork:
    external: true

configs:
  nginx_config:
    file: ./nginx.conf
