input {
  tcp {
    port => 5000
    codec => json_lines {
      target => "log" 
    }
  }
}

filter {
  mutate {
    add_field => { "formatted_time" => "%{@timestamp}" }
  }
  date {
    match => ["formatted_time", "ISO8601"]
    target => "@timestamp"
  }
}

output {
  if [log][service] == "profiles" {
    file {
      path => "/usr/share/logstash/logs/profiles.log"
      codec => line { format => "[%{@timestamp}] %{[log][message]}" }
    }
  } else if [log][service] == "about" {
    file {
      path => "/usr/share/logstash/logs/about.log"
      codec => line { format => "[%{@timestamp}] %{[log][message]}" }
    }
  } else {
    file {
      path => "/usr/share/logstash/logs/other.log"
      codec => line { format => "[%{@timestamp}] %{[log][message]}" }
    }
  }
}